restylers:
  - clang-format:
      enabled: false
  - jq:
      enabled: false # prefer prettier-json
  - prettier:
      include:
        - "src/**/*.js"
  - whitespace:
      include:
        - "**/*"
        - "!dist/index.js"
